/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';

export const SET_SLIDESHOW_IMAGE = 'SET_SLIDESHOW_IMAGE';
export const NEXT_SLIDESHOW_IMAGE = 'NEXT_SLIDESHOW_IMAGE';
export const SET_SLIDESHOW_SET = 'SET_SLIDESHOW_SET';
export const START_SLIDESHOW_SLIDE_ANIMATION = 'START_SLIDESHOW_SLIDE_ANIMATION';
export const STOP_SLIDESHOW_SLIDE_ANIMATION = 'STOP_SLIDESHOW_SLIDE_ANIMATION';